"""add_job_runner_fields_and_runs_table

Revision ID: 42df677d377f
Revises: 61cca42ab2e0
Create Date: 2026-01-11 00:38:48.523651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42df677d377f'
down_revision = '61cca42ab2e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_job_id_fkey'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('events_project_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_project_id_projects'), 'events', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('fk_events_job_id_jobs'), 'events', 'jobs', ['job_id'], ['id'])
    
    # 1. Command Type (Nullable + Backfill + NotNull)
    op.add_column('jobs', sa.Column('command_type', sa.Enum('shell', 'ssh', name='jobcommandtype', create_type=False), nullable=True))
    op.execute("UPDATE jobs SET command_type = 'shell'")
    op.alter_column('jobs', 'command_type', nullable=False)
    
    op.add_column('jobs', sa.Column('target_host', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('target_user', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('credential_key', sa.String(), nullable=True))
    
    # 2. Run Table Updates
    op.add_column('runs', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('runs', sa.Column('stdout', sa.Text(), nullable=True))
    op.add_column('runs', sa.Column('stderr', sa.Text(), nullable=True))
    
    op.execute("UPDATE runs SET started_at = NOW() WHERE started_at IS NULL")
    op.alter_column('runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
               
    op.drop_constraint(op.f('fk_runs_job_id_jobs'), 'runs', type_='foreignkey')
    op.drop_constraint(op.f('fk_runs_triggered_by_id_users'), 'runs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_runs_job_id_jobs'), 'runs', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    
    op.drop_column('runs', 'triggered_by_id')
    op.drop_column('runs', 'created_at')
    op.drop_column('runs', 'finished_at')
    op.drop_column('runs', 'log_content')
    op.drop_column('runs', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
