"""create_events_table_fix

Revision ID: 61cca42ab2e0
Revises: f82ff3a97e0e
Create Date: 2026-01-10 18:24:00.852943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61cca42ab2e0'
down_revision: Union[str, None] = 'f82ff3a97e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
