"""Add command to jobs

Revision ID: 7d39789d63ec
Revises: 65de3e151b24
Create Date: 2026-01-10 11:22:50.475301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d39789d63ec'
down_revision: Union[str, None] = '65de3e151b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add as nullable
    op.add_column('jobs', sa.Column('command', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('working_dir', sa.String(), nullable=True))
    
    # 2. Update existing rows
    op.execute("UPDATE jobs SET command = '' WHERE command IS NULL")
    
    # 3. Alter to not null
    op.alter_column('jobs', 'command', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'working_dir')
    op.drop_column('jobs', 'command')
    # ### end Alembic commands ###
