# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "docker-practice"
  
  # Réseau privé
  config.vm.network "private_network", type: "dhcp"
  
  # Partage de dossier
  config.vm.synced_folder ".", "/vagrant", disabled: false
  
  # Configuration VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.name = "docker-practice-vm"
    vb.memory = 2048
    vb.cpus = 2
  end
  
  # Provisioning avec Ansible
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.inventory_path = "inventory.ini"
    ansible.become = true
  end
end
